### ISSUE TITLE
Automatisches Anstoßen der Berechnung des Orthofotos durch Ablage eines entsprechenden Markers im Verzeichnis der hochgeladenen Bilder am Ende einer Transaktion bzw. eines Flugs

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-automated-orthophotos#1]
**Beschreibung**

Als Entwickler, möchte ich, dass nach dem Abschluss einer Transaktion oder eines Flugs automatisch eine Berechnung des Orthofotos aus den hochgeladenen Bildern angestoßen wird, sodass ich nicht manuell eingreifen muss, um die Erstellung des Orthofotos zu veranlassen. Dies soll geschehen, indem ein spezifischer Marker im Verzeichnis der hochgeladenen Bilder platziert wird, der den Prozess der Orthofoto-Berechnung initiiert.

**Akzeptanzkriterien**

Damit die User Story erfolgreich umgesetzt ist, wird erwartet:

- ... dass das System automatisch einen Marker im Verzeichnis der hochgeladenen Bilder erkennt, sobald eine Transaktion oder ein Flug abgeschlossen ist.
- ... dass die Erkennung des Markers ohne menschliches Eingreifen erfolgt und sofort die Berechnung des Orthofotos auslöst.
- ... dass das System in der Lage ist, aus allen hochgeladenen Bildern eines abgeschlossenen Flugs oder einer Transaktion ein Orthofoto zu berechnen.
- ... dass das System über den Status der Orthofoto-Berechnung in Form eines Logs informiert, einschließlich Erfolgsmeldungen oder etwaiger Fehlermeldungen.

**Comment by Chromeggs** [comment]
Moin  @saschadoemer : ist diese UserStory dein Job oder von Lukas?

**Comment by saschadoemer** [comment]
Da arbeitet Lukas dran, bzw. eine Kombination aus beiden Systemen.

**Comment by Chromeggs** [comment]
Moin @BSO-Lukas : wie ist der Status dieser UserStory?
Das previewed delivery date war der 11.7.
Kannst du das mal aktualisieren?
Thx Ben

**Comment by Vitrum-LL** [comment]
@Chromeggs ist angepasst. Es gibt derzeit noch Probleme mit den Task Options. Die werden derzeit nicht akzeptiert.

**Comment by Chromeggs** [comment]
Moin @BSO-Lukas ,
Gibt es hier News?
Ist das im Übrigen die UserStory, an der du aktuell arbeitest?
Dann würde ich sie eher zu "In progress" verschieben, oder?
Liebe Grüße
Ben

**Comment by Vitrum-LL** [comment]
Moin @Chromeggs ,

hier bitte den handle @Vitrum-LL nutzen der andere ist nur für unsere BSO internen Projekte.  Der Status ist soweit richtig. Derzeit ist der Code im Review. Ich bin gerade an einem neuem Commit dran um die angefragten Changes durchzuführen. 

Habe das Datum weiter nachhinten geschoben.
