### ISSUE TITLE
Benachrichtigung bei Abschluss der automatischen Berechnung des Orthofotos, sodass das Bild über einen entsprechenden Endpunkt zum Download angeboten werden kann

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-automated-orthophotos#2]
**Beschreibung**

Als Datenplattform möchte ich automatisch benachrichtigt werden, wenn die Berechnung des Orthofotos abgeschlossen ist, damit ich sofort weiß, wann das Bild über einen spezifischen Endpunkt zum Download verfügbar ist.

**Akzeptanzkriterien**

Damit die User Story erfolgreich umgesetzt ist, wird erwartet:

- ... dass eine Benachrichtigung an den Endpunkt der Plattform automatisch generiert wird, sobald die Berechnung des Orthofotos abgeschlossen ist.

**Comment by saschadoemer** [comment]
Fertigstellungsdatum für den Endpunkt zur Benachrichtigung bei Abschluss der Berechnungen für das Orthofoto.

**Comment by Chromeggs** [comment]
Moin @saschadoemer ,
Diese Userstory war für Auslieferung letzte Woche geplant. 
Falls es länger braucht als gedacht, kannst du das Datuim anpassen?
Cheers
Ben

**Comment by saschadoemer** [comment]
Aufgrund der Zerstörung des Notebooks muss ich leider eine Woche schieben.

**Comment by saschadoemer** [comment]
Teilrealisierung im Projekt: https://github.com/vitrum-connect/5gla-api/pull/245

**Comment by saschadoemer** [comment]
Teilrealisierung im Projekt: https://github.com/vitrum-connect/5gla-camera-integration-script/pull/38
